// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ProjectEncryptionKeysSchema = z.object({
  projectId: z.string(),
  projectKeyCiphertext: z.string(),
  projectKeyIV: z.string(),
  projectKeyTag: z.string(),
  algorithm: z.string(),
  keyEncoding: z.string(),
});

export type TProjectEncryptionKeys = z.infer<typeof ProjectEncryptionKeysSchema>;
export type TProjectEncryptionKeysInsert = Omit<TProjectEncryptionKeys, TImmutableDBKeys>;
export type TProjectEncryptionKeysUpdate = Partial<Omit<TProjectEncryptionKeys, TImmutableDBKeys>>;
