name: Release standalone postgres version
on:
  push:
    tags:
      - "infisical/v*.*.*-postgres"

jobs:
  infisical-standalone:
    name: Build infisical standalone image
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF_NAME#infisical/}"
      - name: ☁️ Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 📦 Install dependencies to test all dependencies
        run: npm ci --only-production
        working-directory: backend
      - name: version output
        run: |
          echo "Output Value: ${{ steps.version.outputs.major }}"
          echo "Output Value: ${{ steps.version.outputs.minor }}"
          echo "Output Value: ${{ steps.version.outputs.patch }}"
          echo "Output Value: ${{ steps.version.outputs.version }}"
          echo "Output Value: ${{ steps.version.outputs.version_type }}"
          echo "Output Value: ${{ steps.version.outputs.increment }}"
      - name: Save commit hashes for tag
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: 🐋 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: Dockerfile.standalone-infisical
          push: true
          tags: |
            akhilmhdh/destruction:latest
            akhilmhdh/destruction:${{ steps.commit.outputs.short }}
            akhilmhdh/destruction:${{ steps.extract_version.outputs.version }}
